apiVersion: v1
kind: ServiceAccount
metadata:
  name: kvm-pool-autoscaler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kvm-pool-autoscaler
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kvm-pool-autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kvm-pool-autoscaler
subjects:
  - kind: ServiceAccount
    name: kvm-pool-autoscaler
