githubConfigUrl: ${ARC_GITHUB_CONFIG_URL}
githubConfigSecret: arc-gha-secret

maxRunners: ${ARC_CONTAINER_MAX_RUNNERS}
minRunners: ${ARC_CONTAINER_MIN_RUNNERS}

containerMode:
  type: kubernetes

template:
  spec:
    nodeSelector:
      nodepool.syscode.dev/type: general
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        securityContext:
          runAsNonRoot: false
